src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title_fr = null;

    #[ORM\Column(length: 255)]
    private ?string $title_de = null;

    #[ORM\Column(length: 255)]
    private ?string $title_it = null;

    #[ORM\Column(length: 255)]
    private ?string $title_fr_slug = null;

    #[ORM\Column(length: 255)]
    private ?string $title_de_slug = null;

    #[ORM\Column(length: 255)]
    private ?string $title_it_slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_fr = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_de = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_it = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: SubCategory::class, orphanRemoval: true)]
    private Collection $subCategories;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $UpdatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'editcategories')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $edit_user = null;

    #[ORM\Column]
    private ?bool $is_visible = null;

    #[ORM\Column]
    private ?int $ranking = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class)]
    private Collection $products;

    public function __construct()
    {
        $this->subCategories = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleFr(): ?string
    {
        return $this->title_fr;
    }

    public function setTitleFr(string $title_fr): static
    {
        $this->title_fr = $title_fr;

        return $this;
    }

    public function getTitleDe(): ?string
    {
        return $this->title_de;
    }

    public function setTitleDe(string $title_de): static
    {
        $this->title_de = $title_de;

        return $this;
    }

    public function getTitleIt(): ?string
    {
        return $this->title_it;
    }

    public function setTitleIt(string $title_it): static
    {
        $this->title_it = $title_it;

        return $this;
    }

    public function getTitleFrSlug(): ?string
    {
        return $this->title_fr_slug;
    }

    public function setTitleFrSlug(string $title_fr_slug): static
    {
        $this->title_fr_slug = $title_fr_slug;

        return $this;
    }

    public function getTitleDeSlug(): ?string
    {
        return $this->title_de_slug;
    }

    public function setTitleDeSlug(string $title_de_slug): static
    {
        $this->title_de_slug = $title_de_slug;

        return $this;
    }

    public function getTitleItSlug(): ?string
    {
        return $this->title_it_slug;
    }

    public function setTitleItSlug(string $title_it_slug): static
    {
        $this->title_it_slug = $title_it_slug;

        return $this;
    }

    public function getDescriptionFr(): ?string
    {
        return $this->description_fr;
    }

    public function setDescriptionFr(string $description_fr): static
    {
        $this->description_fr = $description_fr;

        return $this;
    }

    public function getDescriptionDe(): ?string
    {
        return $this->description_de;
    }

    public function setDescriptionDe(string $description_de): static
    {
        $this->description_de = $description_de;

        return $this;
    }

    public function getDescriptionIt(): ?string
    {
        return $this->description_it;
    }

    public function setDescriptionIt(string $description_it): static
    {
        $this->description_it = $description_it;

        return $this;
    }

    /**
     * @return Collection<int, SubCategory>
     */
    public function getSubCategories(): Collection
    {
        return $this->subCategories;
    }

    public function addSubCategory(SubCategory $subCategory): static
    {
        if (!$this->subCategories->contains($subCategory)) {
            $this->subCategories->add($subCategory);
            $subCategory->setCategory($this);
        }

        return $this;
    }

    public function removeSubCategory(SubCategory $subCategory): static
    {
        if ($this->subCategories->removeElement($subCategory)) {
            // set the owning side to null (unless already changed)
            if ($subCategory->getCategory() === $this) {
                $subCategory->setCategory(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $UpdatedAt): static
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getEditUser(): ?User
    {
        return $this->edit_user;
    }

    public function setEditUser(?User $edit_user): static
    {
        $this->edit_user = $edit_user;

        return $this;
    }

    public function isIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): static
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getRanking(): ?int
    {
        return $this->ranking;
    }

    public function setRanking(int $ranking): static
    {
        $this->ranking = $ranking;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title_fr',TextType::class,[
                'required' => true,
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Entrez un titre',
                ]
            ])
            ->add('title_de',TextType::class,[
                'required' => true,
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Entrez un titre',
                ]
            ])
            ->add('title_it',TextType::class,[
                'required' => true,
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Entrez un titre',
                ]
            ])
            ->add('description_fr',TextareaType::class,[
                'required' => true,
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Entrez une description',
                ]
            ])
            ->add('description_de',TextareaType::class,[
                'required' => true,
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Entrez une description',
                ]
            ])
            ->add('description_it',TextareaType::class,[
                'required' => true,
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Entrez une description',
                ]
            ])
            ->add('ranking',IntegerType::class,[
                'required' => true,
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Entrez un rang',
                ]
            ])
            ->add('is_visible', ChoiceType::class,[
                'required' => true,
                'label' => false,
                'choices' => [
                    'Publier' => true,
                    'Masquer' => false
                ],
                'attr' => [
                    'class' => 'form-control',
                    'value' => true
                ],
                'expanded'=>true
            ])
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/administration/categories')]
class CategoryController extends AbstractController
{
    #[Route('/liste', name: 'app_category_index', methods: ['GET'])]
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('category/index.html.twig', [
            'categories' => $categoryRepository->findAllByRanking(),
        ]);
    }

    #[Route('/nouveau', name: 'app_category_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $category->setTitleFrSlug($slugger->slug($category->getTitleFr()));
            $category->setTitleDeSlug($slugger->slug($category->getTitleDe()));
            $category->setTitleItSlug($slugger->slug($category->getTitleIt()));
            $category->setUser($this->getUser());
            $category->setEditUser($this->getUser());
            $category->setCreatedAt(new \DateTime());
            $category->setUpdatedAt(new \DateTime());
            $entityManager->persist($category);
            $entityManager->flush();
            $this->addFlash('success', 'La catégorie <<'.$category->getTitleFr().'>> est disponible');
            return $this->redirectToRoute('app_category_new');
        }

        return $this->render('category/new.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/details/{id}', name: 'app_category_show', methods: ['GET'])]
    public function show(Category $category): Response
    {
        return $this->render('category/show.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/edition/{id}', name: 'app_category_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Category $category, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $category->setTitleFrSlug($slugger->slug($category->getTitleFr()));
            $category->setTitleDeSlug($slugger->slug($category->getTitleDe()));
            $category->setTitleItSlug($slugger->slug($category->getTitleIt()));
            $category->setEditUser($this->getUser());
            $category->setUpdatedAt(new \DateTime());
            $entityManager->persist($category);
            $entityManager->flush();

            $this->addFlash('success', 'La catégorie <<'.$category->getTitleFr().'>> est disponible');
            return $this->redirectToRoute('app_category_edit', ['id'=>$category->getId()]);
        }

        return $this->render('category/edit.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/suppression/{id}', name: 'app_category_delete', methods: ['POST'])]
    public function delete(Request $request, Category $category, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $entityManager->remove($category);
            $entityManager->flush();
            $this->addFlash('success', 'La catégorie <<'.$category->getTitleFr().'>> a été supprimée');
        }

        return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/category/_delete_form.html.twig
<form method="post" action="{{ path('app_category_delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/category/_form.html.twig
{{ form_start(form) }}
    
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.title_fr) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name">Titre de la catégorie (fr)</label>
        </div>
    </div>
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.title_de) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name">Titre de la catégorie (de)</label>
        </div>
    </div>
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.title_it) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name">Titre de la catégorie (it)</label>
        </div>
    </div>
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.description_fr) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name">Description de la catégorie (fr)</label>
        </div>
    </div>
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.description_de) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name">Description de la catégorie (de)</label>
        </div>
    </div>
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.description_it) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name">Description de la catégorie (it)</label>
        </div>
    </div>
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.ranking) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name"><span title="Disposition ascendante des catégories"><i class="fa fa-question-circle"></i></span> Classement de la catégorie</label>
        </div>
    </div>
    <div class="tp-login-input-box">
        <div class="tp-login-input">
        {{ form_row(form.is_visible) }}
        </div>
        <div class="tp-login-input-title">
        <label for="name">Visibilité de la catégorie</label>
        </div>
    </div>
    <div class="tp-login-bottom">
        <button type="submit" class="tp-login-btn w-100">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/category/edit.html.twig
{% extends 'base/auth_base.html.twig' %}

{% block title %}Edition Catégorie : {{category.titleFr}} - Administration du site{% endblock %}

{% block body %}

<section class="profile__area pb-120" style="background-image: linear-gradient(#e0c184,#000000);">
    <div class="container">

        <section class="breadcrumb__area breadcrumb__style-2 include-bg pt-50 pb-20 text-light">
            <div class="container">
                <div class="row">
                    <div class="col-xxl-12">
                        <div class="breadcrumb__content p-relative z-index-1">
                        <div class="breadcrumb__list has-icon">
                            <span class="breadcrumb-icon">
                                <i class="fa fa-dashboard"></i>
                            </span>
                            <span><a href="{{path('app_custom_index')}}">Tableau de bord</a></span>
                            <span><a href="{{path('app_admin_website')}}">Administration du site</a></span>
                            <span>Catégories</span>
                            <span>Édition</span>
                            <span>{{category.titleFr}}</span>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="tp-login-area pb-140 p-relative z-index-1 fix">
            <div class="tp-login-shape">
                <img class="tp-login-shape-1" src="/assets/img/login/login-shape-1.png" alt="">
                <img class="tp-login-shape-2" src="/assets/img/login/login-shape-2.png" alt="">
                <img class="tp-login-shape-3" src="/assets/img/login/login-shape-3.png" alt="">
            </div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-8 col-lg-10">
                        <div class="tp-login-wrapper">
                        <div class="tp-login-option">

                            {{ form_errors(form) }}

                            {% for message in app.flashes('success') %}

                                <div class="alert alert-dismissible alert-success">

                                    {{ message }}

                                </div>
                                
                            {% endfor %}
                            <a class="tp-logout-btn" href="{{ path('app_category_index') }}"><i class="fa fa-arrow-left"></i> Retour à la liste</a>

                            <div class="tp-login-mail text-center mb-40 mt-2">
                                <p>Editer une catégorie</p>
                            </div>
                            <div class="tp-login-input-wrapper">
                                {{ include('category/_form.html.twig', {'button_label': 'Appliquer'}) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </section>

        
    
    </div>
</section>
{% endblock %}

templates/category/show.html.twig
{% extends 'base/auth_base.html.twig' %}

{% block title %}Détails de la catégorie {{category.titleFr}} - Administration du site{% endblock %}

{% block body %}

<section class="profile__area pt-120 pb-120" style="background-image: linear-gradient(#e0c184,#000000);">
    
    <div class="container">

        <section class="breadcrumb__area breadcrumb__style-2 include-bg pt-50 pb-20 text-light">
            <div class="container">
                <div class="row">
                    <div class="col-xxl-12">
                        <div class="breadcrumb__content p-relative z-index-1">
                        <div class="breadcrumb__list has-icon">
                            <span class="breadcrumb-icon">
                                <i class="fa fa-dashboard"></i>
                            </span>
                            <span><a href="{{path('app_custom_index')}}">Tableau de bord</a></span>
                            <span><a href="{{path('app_admin_website')}}">Administration du site</a></span>
                            <span>Catégories</span>
                            <span>Détails</span>
                            <span>{{category.titleFr}}</span>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="profile__inner p-relative">
            <div class="profile__shape">
                <img class="profile__shape-1" src="/assets/img/login/laptop.png" alt="" >
                <img class="profile__shape-2" src="/assets/img/login/man.png" alt="" >
                <img class="profile__shape-3" src="/assets/img/login/shape-1.png" alt="" >
                <img class="profile__shape-4" src="/assets/img/login/shape-2.png" alt="" >
                <img class="profile__shape-5" src="/assets/img/login/shape-3.png" alt="" >
                <img class="profile__shape-6" src="/assets/img/login/shape-4.png" alt="" >
            </div>
            <div class="row">
                <div class="col-xxl-12 col-lg-12">
                    <div class="profile__tab-content">
                    <div class="tab-content" id="profile-tabContent">
                        <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            <div class="profile__main">
                                <div class="profile__main-info">
                                    <div class="row gx-3">
                                        <table class="table table-bordered table-striped table-responsive mt-2">
                                            <thead>
                                                <tr>
                                                    <td colspan="2">
                                                        <a class="tp-logout-btn" href="{{ path('app_category_index') }}"> <i class="fa fa-arrow-left"></i> Retour à la liste</a>
                                                    </td>
                                                    <td>
                                                        <a href="{{ path('app_category_edit', {'id': category.id}) }}" class="tp-logout-btn"><i class="fa fa-edit text-primary"></i></a>
                                                    </td>
                                                    <td>
                                                        <form method="post" action="{{ path('app_category_delete', {'id': category.id}) }}" onsubmit="return confirm('La suppression est irréversible !');">
                                                            <input type="hidden" name="_method" value="DELETE">
                                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
                                                            <button type="submit" class="tp-logout-btn"><i class="fa fa-trash text-danger"></i></button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <th>Traduction</th>
                                                    <th>Version (FR)</th>
                                                    <th>Version (DE)</th>
                                                    <th>Version (IT)</th>
                                                </tr>
                                                <tr>
                                                    <td>Titre</td>
                                                    <td>{{ category.titleFr|striptags|length > 20 ? category.titleFr|striptags|slice(0, 20) ~ '...' : category.titleFr|striptags }}</td>
                                                    <td>{{ category.titleDe|striptags|length > 20 ? category.titleDe|striptags|slice(0, 20) ~ '...' : category.titleDe|striptags }}</td>
                                                    <td>{{ category.titleIt|striptags|length > 20 ? category.titleIt|striptags|slice(0, 20) ~ '...' : category.titleIt|striptags }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Description</td>
                                                    <td>{{ category.descriptionFr|striptags|length > 60 ? category.descriptionFr|striptags|slice(0, 60) ~ '...' : category.descriptionFr|striptags}}</td>
                                                    <td>{{ category.descriptionDe|striptags|length > 60 ? category.descriptionDe|striptags|slice(0, 60) ~ '...' : category.descriptionDe|striptags}}</td>
                                                    <td>{{ category.descriptionIt|striptags|length > 60 ? category.descriptionIt|striptags|slice(0, 60) ~ '...' : category.descriptionIt|striptags}}</td>
                                                </tr>
                                                <tr>
                                                    <td>Création le</td>
                                                    <td colspan="3">{{ category.createdAt ? category.createdAt|date('d/m/Y H:i:s') : '' }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Dernière modification le</td>
                                                    <td colspan="3">{{ category.updatedAt ? category.updatedAt|date('d/m/Y H:i:s') : '' }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Rang <span title="Disposition ascendante des catégories"><i class="fa fa-question-circle"></i></span></td>
                                                    <td colspan="3">{{ category.ranking|number_format(0, '.', ' ') }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Publié</td>
                                                    <td colspan="3">
                                                        {% if category.isVisible == true %}
                                                        <span class="text-success">Oui</span>
                                                        {% else %}
                                                            <span class="text-danger">Non</span>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Créateur du contenu</td>
                                                    <td colspan="3">
                                                        {% if app.user.email == category.user.email %}
                                                            <span>Vous</span> (<a class="text-primary" href="mailto:{{category.user.email}}">{{category.user.email}}</a>)
                                                        {% else %}
                                                            <a class="text-primary" href="mailto:{{category.user.email}}">{{category.user.email}}</a>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Dernier administrateur</td>
                                                    <td colspan="3">
                                                        {% if app.user.email == category.user.email %}
                                                            <span>Vous</span> (<a class="text-primary" href="mailto:{{category.user.email}}">{{category.user.email}}</a>)
                                                        {% else %}
                                                            <a class="text-primary" href="mailto:{{category.user.email}}">{{category.user.email}}</a>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</section>

{% endblock %}