src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title_fr = null;

    #[ORM\Column(length: 255)]
    private ?string $title_de = null;

    #[ORM\Column(length: 255)]
    private ?string $title_it = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $short_description_fr = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $short_description_de = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $short_description_it = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_fr = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_de = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_it = null;

    #[ORM\Column]
    private ?bool $is_visible = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $sale_price = null;

    #[ORM\Column]
    private ?bool $is_sale_price = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ProductCondition $condition_value = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ProductAvailability $availability = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?SubCategory $sub_category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'editProducts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $edit_user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleFr(): ?string
    {
        return $this->title_fr;
    }

    public function setTitleFr(string $title_fr): static
    {
        $this->title_fr = $title_fr;

        return $this;
    }

    public function getTitleDe(): ?string
    {
        return $this->title_de;
    }

    public function setTitleDe(string $title_de): static
    {
        $this->title_de = $title_de;

        return $this;
    }

    public function getTitleIt(): ?string
    {
        return $this->title_it;
    }

    public function setTitleIt(string $title_it): static
    {
        $this->title_it = $title_it;

        return $this;
    }

    public function getShortDescriptionFr(): ?string
    {
        return $this->short_description_fr;
    }

    public function setShortDescriptionFr(string $short_description_fr): static
    {
        $this->short_description_fr = $short_description_fr;

        return $this;
    }

    public function getShortDescriptionDe(): ?string
    {
        return $this->short_description_de;
    }

    public function setShortDescriptionDe(string $short_description_de): static
    {
        $this->short_description_de = $short_description_de;

        return $this;
    }

    public function getShortDescriptionIt(): ?string
    {
        return $this->short_description_it;
    }

    public function setShortDescriptionIt(string $short_description_it): static
    {
        $this->short_description_it = $short_description_it;

        return $this;
    }

    public function getDescriptionFr(): ?string
    {
        return $this->description_fr;
    }

    public function setDescriptionFr(string $description_fr): static
    {
        $this->description_fr = $description_fr;

        return $this;
    }

    public function getDescriptionDe(): ?string
    {
        return $this->description_de;
    }

    public function setDescriptionDe(string $description_de): static
    {
        $this->description_de = $description_de;

        return $this;
    }

    public function getDescriptionIt(): ?string
    {
        return $this->description_it;
    }

    public function setDescriptionIt(string $description_it): static
    {
        $this->description_it = $description_it;

        return $this;
    }

    public function isIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): static
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getSalePrice(): ?float
    {
        return $this->sale_price;
    }

    public function setSalePrice(float $sale_price): static
    {
        $this->sale_price = $sale_price;

        return $this;
    }

    public function isIsSalePrice(): ?bool
    {
        return $this->is_sale_price;
    }

    public function setIsSalePrice(bool $is_sale_price): static
    {
        $this->is_sale_price = $is_sale_price;

        return $this;
    }

    public function getConditionValue(): ?ProductCondition
    {
        return $this->condition_value;
    }

    public function setConditionValue(?ProductCondition $condition_value): static
    {
        $this->condition_value = $condition_value;

        return $this;
    }

    public function getAvailability(): ?ProductAvailability
    {
        return $this->availability;
    }

    public function setAvailability(?ProductAvailability $availability): static
    {
        $this->availability = $availability;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getSubCategory(): ?SubCategory
    {
        return $this->sub_category;
    }

    public function setSubCategory(?SubCategory $sub_category): static
    {
        $this->sub_category = $sub_category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getEditUser(): ?User
    {
        return $this->edit_user;
    }

    public function setEditUser(?User $edit_user): static
    {
        $this->edit_user = $edit_user;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title_fr')
            ->add('title_de')
            ->add('title_it')
            ->add('short_description_fr')
            ->add('short_description_de')
            ->add('short_description_it')
            ->add('description_fr')
            ->add('description_de')
            ->add('description_it')
            ->add('is_visible')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('price')
            ->add('sale_price')
            ->add('is_sale_price')
            ->add('condition_value')
            ->add('availability')
            ->add('category')
            ->add('sub_category')
            ->add('user')
            ->add('edit_user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/product')]
class ProductController extends AbstractController
{
    #[Route('/', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_product_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_product_show', methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_product_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_product_delete', methods: ['POST'])]
    public function delete(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
    <h1>Product index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title_fr</th>
                <th>Title_de</th>
                <th>Title_it</th>
                <th>Short_description_fr</th>
                <th>Short_description_de</th>
                <th>Short_description_it</th>
                <th>Description_fr</th>
                <th>Description_de</th>
                <th>Description_it</th>
                <th>Is_visible</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>Price</th>
                <th>Sale_price</th>
                <th>Is_sale_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.titleFr }}</td>
                <td>{{ product.titleDe }}</td>
                <td>{{ product.titleIt }}</td>
                <td>{{ product.shortDescriptionFr }}</td>
                <td>{{ product.shortDescriptionDe }}</td>
                <td>{{ product.shortDescriptionIt }}</td>
                <td>{{ product.descriptionFr }}</td>
                <td>{{ product.descriptionDe }}</td>
                <td>{{ product.descriptionIt }}</td>
                <td>{{ product.isVisible ? 'Yes' : 'No' }}</td>
                <td>{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ product.updatedAt ? product.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.salePrice }}</td>
                <td>{{ product.isSalePrice ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_product_show', {'id': product.id}) }}">show</a>
                    <a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="17">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_product_new') }}">Create new</a>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('app_product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Title_fr</th>
                <td>{{ product.titleFr }}</td>
            </tr>
            <tr>
                <th>Title_de</th>
                <td>{{ product.titleDe }}</td>
            </tr>
            <tr>
                <th>Title_it</th>
                <td>{{ product.titleIt }}</td>
            </tr>
            <tr>
                <th>Short_description_fr</th>
                <td>{{ product.shortDescriptionFr }}</td>
            </tr>
            <tr>
                <th>Short_description_de</th>
                <td>{{ product.shortDescriptionDe }}</td>
            </tr>
            <tr>
                <th>Short_description_it</th>
                <td>{{ product.shortDescriptionIt }}</td>
            </tr>
            <tr>
                <th>Description_fr</th>
                <td>{{ product.descriptionFr }}</td>
            </tr>
            <tr>
                <th>Description_de</th>
                <td>{{ product.descriptionDe }}</td>
            </tr>
            <tr>
                <th>Description_it</th>
                <td>{{ product.descriptionIt }}</td>
            </tr>
            <tr>
                <th>Is_visible</th>
                <td>{{ product.isVisible ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ product.updatedAt ? product.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ product.price }}</td>
            </tr>
            <tr>
                <th>Sale_price</th>
                <td>{{ product.salePrice }}</td>
            </tr>
            <tr>
                <th>Is_sale_price</th>
                <td>{{ product.isSalePrice ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_product_index') }}">back to list</a>

    <a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}