src/Entity/ProductAvailability.php
<?php

namespace App\Entity;

use App\Repository\ProductAvailabilityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductAvailabilityRepository::class)]
class ProductAvailability
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title_fr = null;

    #[ORM\Column(length: 255)]
    private ?string $title_de = null;

    #[ORM\Column(length: 255)]
    private ?string $title_it = null;

    #[ORM\Column]
    private ?bool $is_available = null;

    #[ORM\OneToMany(mappedBy: 'availability', targetEntity: Product::class, orphanRemoval: true)]
    private Collection $products;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'productAvailabilities')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'editProductAvailabilities')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $edit_user = null;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleFr(): ?string
    {
        return $this->title_fr;
    }

    public function setTitleFr(string $title_fr): static
    {
        $this->title_fr = $title_fr;

        return $this;
    }

    public function getTitleDe(): ?string
    {
        return $this->title_de;
    }

    public function setTitleDe(string $title_de): static
    {
        $this->title_de = $title_de;

        return $this;
    }

    public function getTitleIt(): ?string
    {
        return $this->title_it;
    }

    public function setTitleIt(string $title_it): static
    {
        $this->title_it = $title_it;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available): static
    {
        $this->is_available = $is_available;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setAvailability($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getAvailability() === $this) {
                $product->setAvailability(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getEditUser(): ?User
    {
        return $this->edit_user;
    }

    public function setEditUser(?User $edit_user): static
    {
        $this->edit_user = $edit_user;

        return $this;
    }
}

src/Form/ProductAvailabilityType.php
<?php

namespace App\Form;

use App\Entity\ProductAvailability;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductAvailabilityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title_fr')
            ->add('title_de')
            ->add('title_it')
            ->add('is_available')
            ->add('created_at')
            ->add('updated_at')
            ->add('user')
            ->add('edit_user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProductAvailability::class,
        ]);
    }
}

src/Controller/ProductAvailabilityController.php
<?php

namespace App\Controller;

use App\Entity\ProductAvailability;
use App\Form\ProductAvailabilityType;
use App\Repository\ProductAvailabilityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/product/availability')]
class ProductAvailabilityController extends AbstractController
{
    #[Route('/', name: 'app_product_availability_index', methods: ['GET'])]
    public function index(ProductAvailabilityRepository $productAvailabilityRepository): Response
    {
        return $this->render('product_availability/index.html.twig', [
            'product_availabilities' => $productAvailabilityRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_product_availability_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $productAvailability = new ProductAvailability();
        $form = $this->createForm(ProductAvailabilityType::class, $productAvailability);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($productAvailability);
            $entityManager->flush();

            return $this->redirectToRoute('app_product_availability_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product_availability/new.html.twig', [
            'product_availability' => $productAvailability,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_product_availability_show', methods: ['GET'])]
    public function show(ProductAvailability $productAvailability): Response
    {
        return $this->render('product_availability/show.html.twig', [
            'product_availability' => $productAvailability,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_product_availability_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ProductAvailability $productAvailability, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProductAvailabilityType::class, $productAvailability);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_product_availability_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product_availability/edit.html.twig', [
            'product_availability' => $productAvailability,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_product_availability_delete', methods: ['POST'])]
    public function delete(Request $request, ProductAvailability $productAvailability, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$productAvailability->getId(), $request->request->get('_token'))) {
            $entityManager->remove($productAvailability);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_product_availability_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/product_availability/_delete_form.html.twig
<form method="post" action="{{ path('app_product_availability_delete', {'id': product_availability.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product_availability.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product_availability/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product_availability/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ProductAvailability{% endblock %}

{% block body %}
    <h1>Edit ProductAvailability</h1>

    {{ include('product_availability/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_product_availability_index') }}">back to list</a>

    {{ include('product_availability/_delete_form.html.twig') }}
{% endblock %}

templates/product_availability/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductAvailability index{% endblock %}

{% block body %}
    <h1>ProductAvailability index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title_fr</th>
                <th>Title_de</th>
                <th>Title_it</th>
                <th>Is_available</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product_availability in product_availabilities %}
            <tr>
                <td>{{ product_availability.id }}</td>
                <td>{{ product_availability.titleFr }}</td>
                <td>{{ product_availability.titleDe }}</td>
                <td>{{ product_availability.titleIt }}</td>
                <td>{{ product_availability.isAvailable ? 'Yes' : 'No' }}</td>
                <td>{{ product_availability.createdAt ? product_availability.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ product_availability.updatedAt ? product_availability.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_product_availability_show', {'id': product_availability.id}) }}">show</a>
                    <a href="{{ path('app_product_availability_edit', {'id': product_availability.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_product_availability_new') }}">Create new</a>
{% endblock %}

templates/product_availability/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ProductAvailability{% endblock %}

{% block body %}
    <h1>Create new ProductAvailability</h1>

    {{ include('product_availability/_form.html.twig') }}

    <a href="{{ path('app_product_availability_index') }}">back to list</a>
{% endblock %}

templates/product_availability/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductAvailability{% endblock %}

{% block body %}
    <h1>ProductAvailability</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product_availability.id }}</td>
            </tr>
            <tr>
                <th>Title_fr</th>
                <td>{{ product_availability.titleFr }}</td>
            </tr>
            <tr>
                <th>Title_de</th>
                <td>{{ product_availability.titleDe }}</td>
            </tr>
            <tr>
                <th>Title_it</th>
                <td>{{ product_availability.titleIt }}</td>
            </tr>
            <tr>
                <th>Is_available</th>
                <td>{{ product_availability.isAvailable ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ product_availability.createdAt ? product_availability.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ product_availability.updatedAt ? product_availability.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_product_availability_index') }}">back to list</a>

    <a href="{{ path('app_product_availability_edit', {'id': product_availability.id}) }}">edit</a>

    {{ include('product_availability/_delete_form.html.twig') }}
{% endblock %}